services:
  - type: web
    name: redalerta-backend
    runtime: docker
    repo: https://github.com/Cotevarga/RedAlerta
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://localhost:5432/redalerta
      - key: DATABASE_USERNAME
        value: user
      - key: DATABASE_PASSWORD
        value: password
      - key: CORS_ORIGINS
        value: https://red-alerta.vercel.app,http://localhost:5173,http://localhost:5174
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: adminMuni
      - key: ADMIN_PASSWORD
        value: Corral2026
      - key: RENDER_URL
        value: https://redalerta-backend.onrender.com
